[package]
name = "fisix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
lazy_static = "1.4.0"
minifb = "0.23.0"
rand = "0.8.5"
